# Must match the ordering in load_hero_unlock_items()
DOTA2_BASE_ID = 770_1540

PROGRESSIVE_GROUP_UNLOCK_ID = DOTA2_BASE_ID
PRIMORDIAL_FRAGMENT_ID = DOTA2_BASE_ID + 1
FILLER_ITEM_ID = DOTA2_BASE_ID + 2